---
title: "R Notebook"
output:
  html_document: default
  html_notebook: default
---

This a second exploration of the contest package.


```{r load packages}
library(contest)
library(ggplot2)
library(dplyr, quietly = T)
library(rbenchmark)
```

Initialise parameters
```{r initialise parameters}
params <- list(max_gens = 500,
               males_per_winner = 10,
               num_nests = 100,
               encounter_delta = 1,
               metabolism = 1,
               female_mat_time = 10, 
               maturation_rate = 1,
               mutation_rate = 0.1,
               mutation_sd = 0.01,
               mass_to_energy = 10,
               growth_a = 0.5,
               growth_b = 0.1,
               initial_mass = 5,
               alpha_mean = 0,
               alpha_sd = 3,
               beta_sd = 3,
               beta_max = 10,
               beta_mean = 0,
               verbose = F,
               log_every = 100,
               contest_noise = 0,
               quiet = T)
```

Some benchmarking:
```{r}
t(sapply( c(1, 2, 4, 10), function(i){
  data.frame(encounter_delta =  i, elapsed = benchmark({
    params[["encounter_delta"]] <- i
    do.call(run_simulation, params)
  }, replications = 1)$elapsed)
}))

```
No uncert in fights 
```{r}
params$contest_noise <- 0
run_parallel(params, "encounter_delta", seq(1, 10, 0.25), mc.cores = 4) %>% 
  plyr::rbind.fill(.) %>% # collapse the list of dataframes back down into a single dataframe
  filter(generation == params$max_gens) -> last_no_noise

ggplot(last_no_noise, aes(encounter_delta, alpha)) + geom_point()
ggplot(last_no_noise, aes(encounter_delta, beta)) + geom_point()
```
Now there is noise in the commitment function:
it has the density:
```{r}
ggplot(data.frame(z = rf(1000, 100, 100)), aes(z)) + geom_density()
```
moderate uncert in fights
```{r}
# change mass to energy
params$contest_noise <- 100
run_parallel(params, "encounter_delta", seq(1, 10, 0.25), mc.cores = 4) %>% 
  plyr::rbind.fill(.) %>% # collapse the list of dataframes back down into a single dataframe
  filter(generation == params$max_gens) -> last_contest_noise


ggplot(last_contest_noise, aes(encounter_delta, alpha)) + geom_point()
ggplot(last_contest_noise, aes(encounter_delta, beta)) + geom_point()
ggplot(last_contest_noise, aes(encounter_delta, mass)) + geom_point()
ggplot(last_contest_noise, aes(as.factor(encounter_delta), mass)) + geom_violin()
ggplot(last_contest_noise, aes(encounter_delta, num_fights)) + geom_point() + geom_jitter()
ggplot(last_contest_noise, aes(encounter_delta, num_fights)) + geom_point() + geom_jitter()
```


examples of how changes in contest_noise (ie df) can effect z
in the commitment function

$$
\textbf{Commitment} = \textbf{exp}(\beta) \times (\frac{a\text{.mass}}{b\text{.mass}} \times z)^{\alpha}
$$
$$
z \sim F(\text{contest_noise, contest_noise})
$$
```{r}
plyr::ldply(c(10, 20, 50, 100, 1000), function(x) {data.frame(df = x, z = rf(1000, x,x))}) %>% 
  ggplot(aes(z, col = as.factor(df))) + geom_density()
```
